# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 12:45
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20170502_2208'),
        ('viewflow', '0007_auto_20170502_1751'),
        ('sites', '0003_set_site_domain_and_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCRMProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MasterCRMProfile',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='ClientProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='viewflow.Process')),
                ('text', models.CharField(max_length=150, null=True, verbose_name='Обращение')),
                ('phone', models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('closed', models.BooleanField(default=False, verbose_name='Блабла')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.ClientCRMProfile')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City')),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
            options={
                'verbose_name': 'Обработка клиента',
                'verbose_name_plural': 'Обработка клиента',
            },
            bases=('viewflow.process',),
        ),
        migrations.AddField(
            model_name='clientcrmprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clientcrmprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='clientcrmprofile',
            name='sites',
            field=models.ManyToManyField(to='sites.Site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='clientcrmprofile',
            name='user',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
