# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 17:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_fsm
import geoposition.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('detail', models.CharField(max_length=255, verbose_name='Подробности')),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('geoposition', geoposition.fields.GeopositionField(help_text='Введите полный адрес, вместе с городом', max_length=42, verbose_name='Адресс')),
                ('entrance', models.CharField(blank=True, max_length=4, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=4, null=True, verbose_name='Этаж')),
                ('flat', models.CharField(blank=True, max_length=4, null=True, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('state', django_fsm.FSMField(choices=[('new', 'Новая'), ('approved', 'Принял'), ('handed', 'Передал')], default='new', max_length=50, protected=True, verbose_name='Статус')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('state', django_fsm.FSMField(choices=[('new', 'Новая'), ('approved', 'Принял'), ('ready', 'Приступил')], default='new', max_length=50, protected=True, verbose_name='Статус')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('type', models.CharField(choices=[('in', 'На месте'), ('out', 'Выездная')], max_length=15, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Бонус от суммы заказа')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('expire', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('card_choices', models.CharField(choices=[('VISA', 'Visa'), ('MasterCard', 'MasterCard')], max_length=255, null=True)),
                ('bank_choices', models.CharField(choices=[('AlphaBank', 'AlphaBank'), ('SberBank', 'SberBank')], max_length=255, null=True)),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='Счёт')),
                ('receiver_first_name', models.CharField(max_length=255, null=True, verbose_name='Имя получателя')),
                ('receiver_last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия получателя')),
            ],
            options={
                'verbose_name': 'Пластиковвая карта',
                'verbose_name_plural': 'Пластиковвые карты',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
