# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AddField(
            model_name='crmleed',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='crmleed',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='crmleed',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CRMForm'),
        ),
    ]
