# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 18:32
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('sites', '0003_set_site_domain_and_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCRMProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
                ('sites', models.ManyToManyField(to='sites.Site')),
                ('user', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.RemoveField(
            model_name='crmuserprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='clientprocess',
            options={'verbose_name': 'Процесс обработки клиента', 'verbose_name_plural': 'Процесс обработки клиента'},
        ),
        migrations.AlterField(
            model_name='clientprocess',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.ClientCRMProfile'),
        ),
        migrations.DeleteModel(
            name='CRMUserProfile',
        ),
    ]
