# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170518_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmleed',
            name='service',
            field=models.ManyToManyField(to='service.Service', verbose_name='Услуги'),
        ),
    ]
