# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170520_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmleed',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='crmleed',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='crmleed',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CRMForm'),
        ),
        migrations.AlterField(
            model_name='crmleed',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='crmleed',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
