# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_clientcrmprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprocess',
            options={'verbose_name': 'Обработка клиента', 'verbose_name_plural': 'Обработка клиента'},
        ),
        migrations.AlterField(
            model_name='clientcrmprofile',
            name='phone_number',
            field=models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True, verbose_name='Номер телефона'),
        ),
    ]
