# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170615_1448'),
        ('crm', '0004_auto_20170616_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='trouble',
        ),
        migrations.AddField(
            model_name='price',
            name='trouble',
            field=models.ManyToManyField(blank=True, null=True, to='service.Trouble', verbose_name='Проблема'),
        ),
    ]
