# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170504_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientProcess',
            new_name='AutoCreateClientProcess',
        ),
    ]
