# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170615_1448'),
        ('crm', '0005_auto_20170617_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='trouble',
            field=models.ManyToManyField(blank=True, to='service.Trouble', verbose_name='Проблема'),
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='trouble',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='trouble',
            field=models.ManyToManyField(blank=True, related_name='executant_price', to='service.Trouble', verbose_name='Проблема'),
        ),
    ]
