# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170502_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcrmprofile',
            name='phone_number',
            field=models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clientprocess',
            name='text',
            field=models.CharField(max_length=150, null=True, verbose_name='Обращение'),
        ),
    ]
