# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_autocreateclientprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='status',
        ),
    ]
