# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170504_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='form_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя из формы'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='phone',
            field=models.CharField(help_text='Должен быть указан в междурнародном формате, например +375(XX)XXX-XX-XX', max_length=25, null=True, verbose_name='Телефон из формы'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='text',
            field=models.CharField(max_length=150, null=True, verbose_name='Обращение из формы'),
        ),
    ]
