# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20170504_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='closed',
        ),
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='phone_number',
            field=models.CharField(help_text='Должен быть указан в междурнародном формате, например +375(XX)XXX-XX-XX', max_length=25, null=True, verbose_name='Телефон из формы'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Дозвонился?'),
        ),
    ]
