# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('river', '0009_auto_20170521_1613'),
        ('service', '0004_auto_20170510_2228'),
        ('sites', '0003_set_site_domain_and_name'),
        ('crm', '0006_remove_autocreateclientprocess_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=150, null=True, verbose_name='Имя из формы')),
                ('text', models.CharField(max_length=150, null=True, verbose_name='Обращение из формы')),
                ('type', models.CharField(choices=[('order', 'Заказ'), ('consultation', 'Консультация'), ('complaint', 'Жалоба')], max_length=15, verbose_name='Тип')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('comment', models.CharField(max_length=150, null=True, verbose_name='Комментарий')),
                ('complaint_troube', models.CharField(max_length=150, null=True, verbose_name='Суть жалобы')),
                ('address', geoposition.fields.GeopositionField(max_length=42, null=True, verbose_name='Адресс')),
                ('flat', models.CharField(max_length=4, null=True, verbose_name='Квартира')),
                ('datetime', models.DateTimeField(null=True)),
                ('complaint_project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project', verbose_name='Номер заказа')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
                ('creation_form', models.ManyToManyField(to='crm.CRMForm')),
                ('leed_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город')),
                ('phone_number', models.ManyToManyField(to='crm.PhoneNumber')),
                ('service', models.ManyToManyField(blank=True, to='service.Service')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
                ('trouble', models.ManyToManyField(blank=True, to='service.Trouble')),
            ],
            options={
                'verbose_name': 'Автоматическое создание клиента',
                'verbose_name_plural': 'Автоматическое создание клиентов',
            },
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='complaint_project_id',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='country',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='leed_city',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='service',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='site',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='trouble',
        ),
        migrations.DeleteModel(
            name='AutoCreateClientProcess',
        ),
    ]
