# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('river', '0009_auto_20170521_1613'),
        ('crm', '0007_auto_20170522_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'Заказ'), ('consultation', 'Консультация'), ('complaint', 'Жалоба')], max_length=15, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.RenameModel(
            old_name='ClientCRMProfile',
            new_name='ClientProfile',
        ),
        migrations.RenameModel(
            old_name='CRMForm',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='CRMLeed',
            new_name='Leed',
        ),
        migrations.RenameModel(
            old_name='MasterCRMProfile',
            new_name='MasterProfile',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='complaint_project_id',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='country',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='creation_form',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='leed_city',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='service',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='site',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='crmappeal',
            name='trouble',
        ),
        migrations.DeleteModel(
            name='CRMAppeal',
        ),
        migrations.AddField(
            model_name='appeal',
            name='creation_form',
            field=models.ManyToManyField(blank=True, to='crm.Form'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='leed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Leed'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
