# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170504_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='user',
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='process_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process'),
        ),
    ]
