# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170523_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_comments.Comment'),
        ),
    ]
