# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('crm', '0009_auto_20170523_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='address',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город'),
        ),
    ]
