# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170504_2018'),
        ('crm', '0010_auto_20170504_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='troubles',
            field=models.ManyToManyField(to='service.Service'),
        ),
    ]
