# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_auto_20170523_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.Source')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источник',
            },
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='country',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='site',
        ),
        migrations.AddField(
            model_name='appeal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Source'),
        ),
    ]
