# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20170523_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ClientProfile'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name='Статус'),
        ),
    ]
