# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20170523_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leed',
            old_name='comment',
            new_name='text',
        ),
    ]
