# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170510_2228'),
        ('crm', '0015_auto_20170524_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifed_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', geoposition.fields.GeopositionField(max_length=42, verbose_name='Адресс выезда')),
                ('entrance', models.CharField(blank=True, max_length=4, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=4, null=True, verbose_name='Этаж')),
                ('flat', models.CharField(blank=True, max_length=4, null=True, verbose_name='Квартира')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifed_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('type', models.CharField(choices=[('in', 'На месте'), ('out', 'Выездная')], max_length=15, verbose_name='Тип')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Address')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ClientProfile', verbose_name='Клиент')),
                ('service', models.ManyToManyField(to='service.Service', verbose_name='Услуги')),
                ('trouble', models.ManyToManyField(to='service.Trouble', verbose_name='Проблемы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='appeal',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='creation_form',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='project',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Откуда Вы он нас узнали?', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='address',
            name='activities',
            field=models.ManyToManyField(related_name='_address_activities_+', to='crm.Activity'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='assigment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Assignment', verbose_name='Заявка'),
        ),
    ]
