# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20170524_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='address',
            name='geoposition',
            field=geoposition.fields.GeopositionField(default='', max_length=42, verbose_name='Адресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Complaint', verbose_name='Жалоба'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project'),
        ),
    ]
