# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20170526_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='trouble',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='assigment',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='troube',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
