# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170510_2228'),
        ('crm', '0018_auto_20170526_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifed_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('type', models.CharField(choices=[('in', 'На месте'), ('out', 'Выездная')], max_length=15, verbose_name='Тип')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ClientProfile', verbose_name='Клиент')),
                ('service', models.ManyToManyField(to='service.Service', verbose_name='Услуги')),
                ('trouble', models.ManyToManyField(to='service.Trouble', verbose_name='Проблемы')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='appeal',
            name='assigment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Assignment', verbose_name='Заявка'),
        ),
    ]
