# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_assignment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='trouble',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='assigment',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
