# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20170526_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='modifed_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='modifed_at',
        ),
    ]
