# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20170526_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='modifed_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='modifed_at',
        ),
        migrations.RemoveField(
            model_name='leed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leed',
            name='modifed_at',
        ),
    ]
