# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:55
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20170526_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='crm.MasterProfile'),
        ),
    ]
