# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0027_auto_20170526_0755'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='modifed_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
