# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20170526_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='activities',
        ),
        migrations.AlterModelManagers(
            name='clientprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='address',
        ),
    ]
