# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:23
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20170526_0818'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='activities',
            field=models.ManyToManyField(related_name='_address_activities_+', to='crm.Activity'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Address'),
        ),
    ]
