# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20170526_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='assigment',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='complaint',
        ),
        migrations.AddField(
            model_name='assignment',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Appeal', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Appeal', verbose_name='Обращение'),
        ),
    ]
