# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20170527_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
