# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
