# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20170527_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.MasterProfile', verbose_name='Мастер'),
        ),
    ]
