# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_assignment_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адреса', 'verbose_name_plural': 'Адрес'},
        ),
    ]
