# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0009_auto_20170521_1613'),
        ('crm', '0036_auto_20170527_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Address', verbose_name='Адресс'),
        ),
    ]
