# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:16
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0037_auto_20170527_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='owner',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
