# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:05
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20170527_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='owner',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.MasterProfile', verbose_name='Мастер'),
        ),
    ]
