# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:22
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0040_auto_20170527_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='project',
            name='city',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='project',
            name='master',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site',
        ),
        migrations.AddField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Assignment', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='_project_masters_+', to='crm.MasterProfile', verbose_name='Мастера'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(to='service.Service', verbose_name='Выполненные услуги'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='trouble',
            field=models.ManyToManyField(to='service.Trouble', verbose_name='Решённые проблемы'),
        ),
    ]
