# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_auto_20170529_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created_bys',
            new_name='created_by',
        ),
    ]
