# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_auto_20170529_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
