# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_auto_20170529_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания счёта'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateTimeField(null=True, verbose_name='Дата оплаты'),
        ),
    ]
