# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercrmprofile',
            name='sites',
        ),
    ]
