# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
