# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 15:43
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('sites', '0003_set_site_domain_and_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCRMProfile',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('raiting', models.IntegerField()),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватарка')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
