# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170502_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователль', 'verbose_name_plural': 'Пользователь'},
        ),
    ]
