# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170424_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercrmprofile',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
