# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-01-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mastercrmprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercrmprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватарка'),
        ),
    ]
