# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
