# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_homepage_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMasterPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'master placement',
                'verbose_name_plural': 'master placements',
            },
        ),
        migrations.RemoveField(
            model_name='master',
            name='master',
        ),
        migrations.AddField(
            model_name='homepagemasterplacement',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.Master'),
        ),
        migrations.AddField(
            model_name='homepagemasterplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_placements', to='cms.HomePage'),
        ),
    ]
