# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170423_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypage',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country'),
        ),
    ]
