BBBBBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBB

BBBBB BBBBBBB

  BB BBBBBBB
    XXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXX
  BBBBB

  XXXXX XXXXXXXXXXXXX XXXXXXXXXX
      BBBBBBBBBB
      
      XXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
  XXXXXXX

XXXXXX

BBBBBBBBBBBBBBB BBBBBB
BBBBBBBBBBBBBB
BBBBBBBB BBBBBBB
