BBBBBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB

BB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXX
BBBB
    BB BBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
    XXXX XXXXXXXXXXXXXXXXXXX
    BBBBB
BBBBB


BB BBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
BBBBB
 #
 #
 #
 #
 #
 #
 #
 #
 #


XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBB
      XXXX XXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBXXBB BBBBBBBBBBBBB BB BBBB XXXX BBBB BBBBBXXXXX XXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBB BBB BBB BBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
      XXXXXXXXXXXX XXXXXXXXXXXX
      XXXXFFFFFFFFXXXXX
      XXX
      BB BBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      BBBB
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBB
      XXXX
    XXXXXX
  XXXXXX
XXXXXX
BB BBBBBBBBBBBBB
  XXXXXXXXXXXXXXXXXXXX
  BBB BBBBBBB BB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            BBBB
                XXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXX
            BBBBB
    XXXXXXFFFFFFFFXXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBXXBB BBBBBBBBBBBB BB BBBB XX BBBBBBBBBXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBB BB BBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
    XXXXXX
  XXXXXX
  BBBBBB
BBBBB
BB BBBBBBB
  XXXXXXXXXXXXXXX
  XXXXX

    BBB BBBBBB BB BBBBBBB
    XXXX XXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBB BB BBBB
      XXXX XXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXX XXXXXXXXXXXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
      BBBBB
      XXXX XXXXX XXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBB BB BBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
            XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB
          BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXFFFFFFFFXXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBXXBB BBBBBBBBBBBBBBB BB BBBBBBB XX BBBBBBBBBXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBB BB BBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
          XXXX
          BBBBBB
        BBBBB
      XXXXXX
          XXXX XXXXX XXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            BBBB
                XXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXX
            BBBBB
            XX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBXXBB BBBBBBBBBBBBBB BB BBBBBBB XX BBBBBBBBBXXXX XXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBB
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                BBBB
                    BB  BBBBBBBBBBBBB BB BBBB
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                BBBBB
          XXXXXX
    XXXXXX
  XXXX
    BBBBBB


BBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
BBBBB

BB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXX
      BBBBBB
    XXXXXX
    XXXXXX
BBBBB

BBBBBBBB BBBBBBB
BBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXX XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX
XXXXXXXXX
BBBBBBBB BBBBBBBB
