# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170504_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Тип оплаты', 'verbose_name_plural': 'Типы оплаты'},
        ),
    ]
