# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170504_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocreateclientprocess',
            options={'verbose_name': 'Автоматическое создание клиента', 'verbose_name_plural': 'Автоматическое создание клиентов'},
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
