# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0007_auto_20170502_1751'),
        ('crm', '0011_autocreateclientprocess_troubles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCreateProjectProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='bill_of_payer',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clientcrmprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.PaymentType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='phone',
            field=models.ManyToManyField(to='crm.PhoneNumber', verbose_name='Номера телефонов'),
        ),
        migrations.AddField(
            model_name='clientcrmprofile',
            name='phone_number',
            field=models.ManyToManyField(to='crm.PhoneNumber', verbose_name='Номера телефонов'),
        ),
    ]
