# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('crm', '0012_auto_20170506_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
    ]
