# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_autocreateclientprocess_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='creation_form',
            field=models.CharField(max_length=150, null=True, verbose_name='Форма создания'),
        ),
    ]
