# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_autocreateclientprocess_creation_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autocreateclientprocess',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
