# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0007_auto_20170502_1751'),
        ('crm', '0016_remove_autocreateclientprocess_troubles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocreateprojectprocess',
            name='process_ptr',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='sites',
        ),
        migrations.DeleteModel(
            name='AutoCreateProjectProcess',
        ),
    ]
