# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20170506_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='phone_number',
            field=models.ManyToManyField(to='crm.PhoneNumber', verbose_name='Номера телефонов'),
        ),
    ]
