# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('crm', '0018_autocreateclientprocess_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
