# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20170506_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autocreateclientprocess',
            old_name='phone_number',
            new_name='phone_number1',
        ),
    ]
