# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_trouble'),
        ('crm', '0021_auto_20170506_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='service',
            field=models.ManyToManyField(to='service.Service'),
        ),
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='trouble',
            field=models.ManyToManyField(to='service.Trouble'),
        ),
    ]
