# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 17:35
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20170506_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocreateclientprocess',
            name='address',
            field=geoposition.fields.GeopositionField(default='', max_length=42, verbose_name='Адресс'),
            preserve_default=False,
        ),
    ]
