# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_autocreateclientprocess_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='form_phone_number',
            field=models.CharField(help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, verbose_name='Номер телефона из формы'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='phone_number1',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, unique=True, verbose_name='Номер телефона для связи №1'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='phone_number2',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, unique=True, verbose_name='Номер телефона для связи №2'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='phone_number3',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, unique=True, verbose_name='Номер телефона для связи №3'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='phone_number4',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, unique=True, verbose_name='Номер телефона для связи №4'),
        ),
        migrations.AlterField(
            model_name='autocreateclientprocess',
            name='phone_number5',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, unique=True, verbose_name='Номер телефона для связи №5'),
        ),
    ]
