# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20170506_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocreateclientprocess',
            name='city',
        ),
    ]
