# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('crm', '0027_remove_autocreateclientprocess_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcrmprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientcrmprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientcrmprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientcrmprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clientcrmprofile',
            name='sites',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=geoposition.fields.GeopositionField(default='', max_length=42, verbose_name='Адресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Сайт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
