# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20170508_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_phone_number',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, verbose_name='Номер телефона для связи №5'),
        ),
    ]
