# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_project_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
