# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20170508_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.MasterCRMProfile'),
        ),
    ]
