# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 20:51
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_process_city'),
        ('sites', '0003_set_site_domain_and_name'),
        ('crm', '0031_auto_20170508_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCreateProjectProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='viewflow.Process')),
                ('text', models.CharField(max_length=150, null=True, verbose_name='Обращение')),
                ('phone', models.CharField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=25, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Дозвонился?')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('closed', models.BooleanField(default=False, verbose_name='Блабла')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.ClientCRMProfile')),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
            options={
                'verbose_name': 'Автоматическое создание заказа',
                'verbose_name_plural': 'Автоматическое создание заказов',
            },
            bases=('viewflow.process',),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, verbose_name='Номер телефона для связи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone_number',
            field=models.CharField(blank=True, help_text='Должен быть в международном формате, например +375(25)907-50-55', max_length=25, null=True, verbose_name='Номер телефона для связи'),
        ),
    ]
