# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trouble',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
