# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
