# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_troubles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='troubles',
            field=models.ManyToManyField(related_name='service', to='service.Trouble'),
        ),
    ]
