# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170701_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='troubles',
            field=models.ManyToManyField(blank=True, related_name='service', to='service.Trouble'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
