# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20170704_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
