# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20170705_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='УТП'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='service.Service', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='troubles',
            field=models.ManyToManyField(blank=True, related_name='service', to='service.Trouble', verbose_name='Проблемы, которые решает эта услуга'),
        ),
    ]
