# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20170706_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
    ]
