# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20170706_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='service',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Device', verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='service',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.SparePart', verbose_name='Запчасти'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Brand', verbose_name='Бренд'),
        ),
    ]
