# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('service', '0013_auto_20170706_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ManyToManyField(to='cities_light.City'),
        ),
    ]
