# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_service_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trouble',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='brand',
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ManyToManyField(blank=True, to='service.Brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.ManyToManyField(to='cities_light.City', verbose_name='Города'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='device',
        ),
        migrations.AddField(
            model_name='service',
            name='device',
            field=models.ManyToManyField(blank=True, to='service.Device', verbose_name='Устройства'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='spare_part',
        ),
        migrations.AddField(
            model_name='service',
            name='spare_part',
            field=models.ManyToManyField(blank=True, to='service.SparePart', verbose_name='Запчасти'),
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='brand',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='brand',
            field=models.ManyToManyField(blank=True, to='service.Brand', verbose_name='Бренд'),
        ),
    ]
