# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20170706_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='city',
            new_name='cities',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='device',
            new_name='devices',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='spare_part',
            new_name='spare_parts',
        ),
    ]
