# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20170706_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
    ]
