# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20170708_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='devices',
            field=models.ManyToManyField(blank=True, to='service.Device', verbose_name='Устройства'),
        ),
    ]
