BBBB BBBBBBBBB BBBBBBBBBBBBBBBB
BBBBBBBBBBBBB BB BBBBBBBBB
    BBB BBBBBBBB BB BBBBBBBBB
        XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBBB BBBBBBBBBBBBBBB XXXXXXBBBBBXX
            BB BBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
                    BBBB
                        XX XXXXXXBBBBBBB BBBBBBBBXXXXXX
                    BBBBB
        XXXXX       
    BBBBBB
