BBBB BBBBBBBBB BBBBBBBBBBBBBBBB
BBBBBBBBBBBBB BB BBBBBBBBB


XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            
            XX XXXXXXBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXX XXXXXXXXXX XXXXXXXXXXXX
                BBB BBBBBBBB BB BBBBBBBBB
                    XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBBB BBBBBBBBBBBBBBB XXXXXXBBBBBXX
                        BB BBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
                            BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
                        BBBB
                            XX XXXXXXBBBBBBB BBBBBBBBXXXXXX
                        BBBBB
                    XXXXX       
                BBBBBB
            XXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX