# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mastercrmprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercrmprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='/home/narnik/Программы/DjangoProjects/gglobal/gglobal/media', verbose_name='Аватарка'),
        ),
    ]
