# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('users', '0003_auto_20170502_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cities_light.City'),
        ),
    ]
