# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170424_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercrmprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mastercrmprofile',
            name='country',
        ),
    ]
