# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API_KEY')),
                ('bot_id', models.CharField(max_length=255, verbose_name='id')),
                ('first_name', models.CharField(max_length=255, verbose_name='first_name')),
                ('username', models.CharField(max_length=255, verbose_name='first_name')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='пользователь')),
                ('unique_code', models.CharField(max_length=255, verbose_name='unique code')),
            ],
        ),
    ]
