# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='chat id')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('message_id', models.CharField(max_length=255, verbose_name='message id')),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmb.Chat', verbose_name='chat id')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmb.User'),
        ),
    ]
