# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 00:52
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0004_auto_20170613_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
