# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0005_auto_20170613_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Авторизован'),
        ),
    ]
