# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
