# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('1', 'Bronze'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Diamond')], max_length=1)),
                ('icon', models.ImageField(upload_to='badge_images')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.Badge')),
            ],
        ),
    ]
