# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170520_1409'),
        ('cms', '0004_mastercrmprofilepage_mastersindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercrmprofilepage',
            name='master',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.MasterCRMProfile'),
        ),
    ]
