# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('cms', '0004_auto_20170419_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
