# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_homepage_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
