# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170521_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterCRMProfilePage',
            new_name='MasterProfilePage',
        ),
    ]
