# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170618_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepage',
            name='body',
        ),
    ]
