# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mastercrmprofile_avatar'),
        ('cms', '0006_auto_20170419_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.MasterCRMProfile')),
            ],
        ),
    ]
