# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 23:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20170622_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citypagesnippetplacement',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='pagesnippet',
            options={'verbose_name': 'Сниппет для базовой страницы', 'verbose_name_plural': 'Сниппеты для базовых страниц'},
        ),
        migrations.AlterModelOptions(
            name='pagesnippetplacement',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='citypagesnippetplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_page_snippet_placements', to='cms.CityPage'),
        ),
        migrations.AlterField(
            model_name='pagesnippetplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_page_snippet_placements', to='cms.BasePage'),
        ),
    ]
