# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20170419_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='master',
            field=models.ManyToManyField(blank=True, to='users.MasterCRMProfile'),
        ),
    ]
