# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20170623_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Service'),
        ),
    ]
