# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170419_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.Master'),
        ),
    ]
