# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20170623_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trouble',
            name='trouble',
        ),
        migrations.AlterField(
            model_name='troublepage',
            name='trouble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Trouble'),
        ),
    ]
