# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20170623_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сниппет для страницы услуги', 'verbose_name_plural': 'Сниппеты для страниц услуг'},
        ),
        migrations.AlterModelOptions(
            name='trouble',
            options={'verbose_name': 'Сниппет для страницы проблемы', 'verbose_name_plural': 'Сниппеты для страниц проблем'},
        ),
    ]
