# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20170623_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysnippetpage',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сниппета'),
        ),
        migrations.AlterField(
            model_name='pagesnippet',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сниппета'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сниппета'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название сниппета'),
        ),
    ]
