# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170702_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='snippets',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='snippets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.ServiceSnippet'),
        ),
    ]
