# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20170702_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='snippets',
            new_name='snippet',
        ),
    ]
