# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20170702_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Страница услуги', 'verbose_name_plural': 'Страницы услуг'},
        ),
    ]
