# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('viewflow', '0005_rename_flowcls'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
