# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import viewflow.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_auto_20170427_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='process',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='process',
            name='flow_class',
            field=viewflow.fields.FlowReferenceField(max_length=250, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(default='НОВАЯ', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='task',
            name='external_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='task',
            name='flow_task_type',
            field=models.CharField(max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner_permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Права ответственного'),
        ),
        migrations.AlterField(
            model_name='task',
            name='started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начат'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(db_index=True, default='НОВАЯ', max_length=50, verbose_name='Статус'),
        ),
    ]
