# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_task_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='city',
        ),
    ]
