# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 00:31
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20170427_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='comment_text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
