# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('qa', '0003_remove_question_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
